dashboard/config/routes.rb
    # of the sharing user in the URL. Doing so allows us to block showing the level source if the user
    # deletes themself.
    resources :obfuscated_level_sources, path: '/r/', controller: :level_sources, param: :level_source_id_and_user_id, only: [:show, :edit, :update] do
      member do
        get 'generate_image'
        get 'original_image'
      end
    end

    get '/share/:id', to: redirect('/c/%{id}')

    devise_scope :user do
      get '/oauth_sign_out/:provider', to: 'sessions#oauth_sign_out', as: :oauth_sign_out
      post '/users/begin_sign_up', to: 'registrations#begin_sign_up'
      post '/users/finish_sign_up', to: 'registrations#new'
      patch '/dashboardapi/users', to: 'registrations#update'
      patch '/users/upgrade', to: 'registrations#upgrade'
      patch '/users/set_student_information', to: 'registrations#set_student_information'
      patch '/users/email', to: 'registrations#set_email'
      patch '/users/parent_email', to: 'registrations#set_parent_email'
      patch '/users/user_type', to: 'registrations#set_user_type'
      get '/users/cancel', to: 'registrations#cancel'
      post '/users/auth/:id/disconnect', to: 'authentication_options#disconnect'
      get '/users/migrate_to_multi_auth', to: 'registrations#migrate_to_multi_auth'
      get '/users/demigrate_from_multi_auth', to: 'registrations#demigrate_from_multi_auth'
      get '/users/to_destroy', to: 'registrations#users_to_destroy'
      get '/reset_session', to: 'sessions#reset'
      get '/lockout', to: 'sessions#lockout'
      get '/users/existing_account', to: 'registrations#existing_account'
      get '/users/edit', to: 'registrations#edit'
    end
    devise_for :users, controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      confirmations: 'confirmations',
      sessions: 'sessions',
      passwords: 'passwords'
    }
    get 'discourse/sso' => 'discourse_sso#sso'

    root to: "home#index"
    get '/home_insert', to: 'home#home_insert'
    get '/health_check', to: 'home#health_check'
    namespace :home do
      HomeController.instance_methods(false).each do |action|
        get action, action: action
      end
    end

    resources :p, path: '/p/', only: [:index] do
      collection do
        ProjectsController::STANDALONE_PROJECTS.each do |key, value|
          get '/' + key.to_s, to: 'projects#redirect_legacy', key: value[:name], as: key.to_s
        end
        get '/', to: redirect('/projects')
      end
    end

    get "/gallery", to: redirect("/projects/public")

    get 'projects/featured', to: 'projects#featured'
    delete '/featured_projects/:channel_id', to: 'featured_projects#destroy'
    put '/featured_projects/:channel_id/unfeature', to: 'featured_projects#unfeature'
    put '/featured_projects/:channel_id/feature', to: 'featured_projects#feature'
    put '/featured_projects/:channel_id/bookmark', to: 'featured_projects#bookmark'

    get 'projects/:channel_id/extra_links', to: 'projects#extra_links'

    resources :projects, path: '/projects/', only: [:index] do
      collection do
        ProjectsController::STANDALONE_PROJECTS.each do |key, _|
          get "/#{key}", to: 'projects#load', key: key.to_s, as: "#{key}_project"
          get "/#{key}/new", to: 'projects#create_new', key: key.to_s, as: "#{key}_project_create_new"

          # Weblab projects are shared on a codeprojects path. The share URL on code studio doesn't mean anything and instead
          # should be redirected to the corresponding codeprojects path.
          if key == 'weblab'
            get "/#{key}/:channel_id", constraints: {host: CDO.dashboard_hostname}, to: redirect("//#{CDO.site_host('codeprojects.org')}/%{channel_id}/")
          else
            get "/#{key}/:channel_id", to: 'projects#show', key: key.to_s, as: "#{key}_project_share", share: true
          end

          get "/#{key}/:channel_id/edit", to: 'projects#edit', key: key.to_s, as: "#{key}_project_edit"
          get "/#{key}/:channel_id/view", to: 'projects#show', key: key.to_s, as: "#{key}_project_view", readonly: true
          get "/#{key}/:channel_id/embed", to: 'projects#show', key: key.to_s, as: "#{key}_project_iframe_embed", iframe_embed: true

          # appending 'embed_app_and_code' to a project renders a page with just the app editor. It is distinct from appending 'embed'
          # to a project in that appending 'embed' renders only the app, wheras 'embed_app_and_code renders the app and the workspace
          # for building the app, in view only mode. Specifically, appending 'embed_app_and_code' to a project does the following:
          #
          # - set view options to remove headers/footers
          # - set a view option 'iframeEmbedAppAndCode' to true, setting the config.level.iframeEmbedAppAndCode variable to true on the client side
          #   This makes a number of changes to how StudioApp behaves, and some changes to how P5Lab.js behaves
          get "/#{key}/:channel_id/embed_app_and_code", to: 'projects#show', key: key.to_s, as: "#{key}_project_iframe_embed_app_and_code", iframe_embed_app_and_code: true, readonly: true
          get "/#{key}/:channel_id/remix", to: 'projects#remix', key: key.to_s, as: "#{key}_project_remix"
          get "/#{key}/:channel_id/export_create_channel", to: 'projects#export_create_channel', key: key.to_s, as: "#{key}_project_export_create_channel"
          get "/#{key}/:channel_id/export_config", to: 'projects#export_config', key: key.to_s, as: "#{key}_project_export_config"
          get "/#{key}/:channel_id/can_publish_age_status", to: 'projects#can_publish_age_status'
        end

        get '/:tab_name', to: 'projects#index', constraints: {tab_name: /(public|libraries)/}
      end
    end

    # Get or create a project for the given level_id. Optionally, the request
    # can include script_id to get or create a project for the level and script.
    # Optionally, the request can include user_id to get a project for another user,
    # like a teacher viewing a student's work.
    # The request can also include a script_level_id if the level_id refers to a different level (for example, a sublevel).
    get "projects(/script/:script_id)(/script_level/:script_level_id)/level/:level_id(/user/:user_id)", to: 'projects#get_or_create_for_level'

    post '/locale', to: 'home#set_locale', as: 'locale'

    # quick links for cartoon network arabic
    get '/flappy/lang/ar', to: 'home#set_locale', as: 'flappy/lang/ar', locale: 'ar-SA', user_return_to: '/flappy/1'
    get '/playlab/lang/ar', to: 'home#set_locale', as: 'playlab/lang/ar', locale: 'ar-SA', user_return_to: '/s/playlab/lessons/1/levels/1'
    get '/artist/lang/ar', to: 'home#set_locale', as: 'artist/lang/ar', locale: 'ar-SA', user_return_to: '/s/artist/lessons/1/levels/1'

    # /lang/xx shortcut for all routes
    get '/lang/:locale', to: 'home#set_locale', user_return_to: '/'
    get '*i18npath/lang/:locale', to: 'home#set_locale'

    get 'pools', to: 'pools#index', as: 'pools'
    scope 'pools/:pool' do
      resources :blocks, constraints: {id: /[^\/]+/}
    end
    resources :shared_blockly_functions, path: '/functions'

    get 'helpful_links', to: 'helpful_links#index', as: 'helpful_links'

    resources :libraries do
      collection do
        get '/get_updates', to: 'libraries#get_updates'
      end
    end

    resources :datasets, param: 'dataset_name', constraints: {dataset_name: /[^\/]+/}, only: [:index, :show, :update, :destroy] do
      collection do
        get '/manifest/edit', to: 'datasets#edit_manifest'
        post '/manifest/update', to: 'datasets#update_manifest'
      end
    end

    resources :levels do
      collection do
        get 'get_filtered_levels'
      end
      member do
        get 'get_rubric'
        get 'embed_level'
        get 'edit_blocks/:type', to: 'levels#edit_blocks', as: 'edit_blocks'
        get 'edit_exemplar', to: 'levels#edit_exemplar', as: 'edit_exemplar'
        get 'get_serialized_maze'
        post 'update_properties'
        post 'update_blocks/:type', to: 'levels#update_blocks', as: 'update_blocks'
        post 'clone'
        post 'update_start_code'
        post 'update_exemplar_code'
        get 'level_properties'
        get 'extra_links'
      end
    end

    post 'level_assets/upload', to: 'level_assets#upload'

    resources :level_starter_assets, only: [:show], param: 'level_name', constraints: {level_name: /[^\/]+/} do
      member do
        get '/:filename', to: 'level_starter_assets#file', format: true
        post '', to: 'level_starter_assets#upload'
        delete '/:filename', to: 'level_starter_assets#destroy'
      end
    end

    resources :course_offerings, only: [:edit, :update], param: 'key' do
      collection do
        get 'quick_assign_course_offerings'
      end
    end

    get '/course/:course_name', to: redirect('/courses/%{course_name}')
    get '/courses/:course_name/vocab/edit', to: 'vocabularies#edit'
    # these routes use course_course_name to match generated routes below that are nested within courses
    get '/courses/:course_course_name/guides/edit', to: 'reference_guides#edit_all', as: :edit_all_reference_guides

    resources :courses, param: 'course_name' do
      member do
        get 'vocab'
        get 'resources'
        get 'code'
        get 'standards'
        get 'get_rollup_resources'
      end

      resources :reference_guides, param: 'key', path: 'guides'
    end

    resources :potential_teachers, only: [:create]
    get '/potential_teachers/:id', param: :id, to: 'potential_teachers#show'

    # CSP 20-21 lockable lessons with lesson plan redirects
    get '/s/csp1-2020/lockable/2(*all)', to: redirect(path: '/s/csp1-2020/lessons/14%{all}')
    get '/s/csp2-2020/lockable/1(*all)', to: redirect(path: '/s/csp2-2020/lessons/9%{all}')
    get '/s/csp3-2020/lockable/1(*all)', to: redirect(path: '/s/csp3-2020/lessons/11%{all}')

dashboard/app/views/shared/_check_admin.html.haml
- if @script && Gatekeeper.allows('requires_hoc_secret', where: {script_name: @script.name})
  %script{src: webpack_asset_path('js/shared/_check_admin.js'),
          data: {checkadmin: Digest::MD5.hexdigest(DCDO.get("hoc_secret", '')).to_json}}

dashboard/app/views/shared/_course_tall_block.haml
- show_teacher_guide ||= false
-# the script family the script belongs to.
- family_name ||= nil
- block_data ||= CourseBlockHelper.get_tall_course_block(id, family_name)

- if block_data
  - alt_text = block_data[:image_alt]
  .courseblock-span3.courseblock-tall
    = link_to block_data[:url] do
      = image_tag block_data[:image_url], height: '120px', width: '100%', alt: alt_text
      .course-container
        %h3.heading= block_data[:title]
        - if block_data[:audience]
          .text= block_data[:audience]
        .text.smalltext= block_data[:body]
        - if show_teacher_guide && block_data[:teacher_guide]&.present?
          .teacher-guide= link_to t('view_teacher_guide'), block_data[:teacher_guide]

dashboard/app/views/shared/_course_wide_block.haml
- if id == Unit::HOC_NAME
  .courseblock-span6.courseblock-wide-small
    = link_to hoc_reset_url do
      .courseblock-span2.imgspan
        %img{src: CDO.code_org_url('/images/fit-150x100/codehoc3.jpg')}
      .courseblock-span4.heading
        %h3= t('upsell.hoc.title')
        .smalltext= t('upsell.hoc.body')

- elsif id == Unit::FLAPPY_NAME
  .courseblock-span6.courseblock-wide-small
    = link_to script_reset_url(Unit::FLAPPY_NAME) do
      .courseblock-span2.imgspan
        %img{src: CDO.studio_url('/blockly/media/skins/flappy/small_static_avatar.png')}
      .courseblock-span4.heading
        %h3= t('upsell.flappy.title')
        .smalltext= t('upsell.flappy.body')

- elsif ['applab', 'gamelab', 'widgets', 'weblab'].include? id
  - url = CDO.code_org_url(id)
  .courseblock-span6.courseblock-wide-small{style: "min-height: 215px;"}
    = link_to url do
      .courseblock-span2.imgspan
        %img{src: CDO.code_org_url("/shared/images/courses/fit-130x180/logo_#{id}_tall.jpg")}
      .courseblock-span4.heading
        %h3= t("upsell.#{id}.title")
        %h4= t("upsell.#{id}.audience")
        .smalltext= t("upsell.#{id}.body")
      .bottombar.smalltext.trynow= t("upsell.#{id}.cta")

- elsif id == Unit::TWENTY_HOUR_NAME && view == 'large'
  - url = script_reset_url(id)
  .courseblock-span6.courseblock-wide-large
    = link_to script_url(Unit::TWENTY_HOUR_NAME) do
      .courseblock-span2.imgspan
        %img{src: CDO.code_org_url('/images/fit-150x100/code20hr.jpg')}
      .courseblock-span4.heading
        %h3= t('upsell.20-hour.title')
        %h4= data_t_suffix('script.name', '20-hour', 'description_audience')
        .smalltext= t('upsell.20-hour.body')

- elsif id == Unit::TWENTY_HOUR_NAME && view == 'small'
  - url = script_reset_url(id)
  - audience = data_t_suffix('script.name', id, 'description_audience')
  .courseblock-span6.courseblock-wide-small
    = link_to script_url(Unit::TWENTY_HOUR_NAME) do
      .courseblock-span2.imgspan
        %img{src: CDO.code_org_url('/images/fit-150x100/code20hr.jpg')}
      .courseblock-span4.heading
        %h3= t('upsell.20-hour.title')
        %h4= data_t_suffix('script.name', id, 'description_audience')
        .smalltext= t('upsell.20-hour.body_short')

- elsif id == 'unplugged' && view == 'large'
  - url = CDO.code_org_url("/curriculum/unplugged")
  .courseblock-span6.courseblock-wide-large
    = link_to url do
      .courseblock-span2.imgspan
        %img{src: CDO.code_org_url('/images/fit-150x100/unplugged.png')}
      .courseblock-span4.heading
        %h3= t("upsell.#{id}.title")
        %h4= t("upsell.#{id}.audience")
        .smalltext= t("upsell.#{id}.body")

- elsif id == 'unplugged' && view == 'small'
  - url = CDO.code_org_url("/curriculum/unplugged")
  .courseblock-span6.courseblock-wide-small{style: "min-height: 120px;"}
    = link_to url do
      .courseblock-span2.imgspan
        %img{src: CDO.code_org_url('/images/fit-150x100/unplugged.png')}
      .courseblock-span4.heading
        %h3= t("upsell.#{id}.title")
        %h4= t("upsell.#{id}.audience")
        .smalltext= t("upsell.#{id}.body_short")

- elsif [Unit::ARTIST_NAME, Unit::PLAYLAB_NAME].include? id
  - url = script_reset_url(id)
  - title = data_t_suffix('script.name', id, 'title')
  - body = data_t_suffix('script.name', id, 'description_short')
  .courseblock-span6.courseblock-wide-small{style: "min-height: 100px;"}
    = link_to url do
      .courseblock-span2.imgspan
        %img{src: CDO.code_org_url("/shared/images/courses/fill-150x110/logo_tall_#{id}.jpg")}
      .courseblock-span4.heading
        %h3= title
        .smalltext= body

- elsif [Unit::EXPRESS, Unit::PREEXPRESS].any? {|course| id.match(/^#{course}/)}
  .courseblock-span6.courseblock-wide-small
    = link_to script_url(id)  do
      .courseblock-span2.imgspan
        - image = (family_name.nil?) ? "logo_tall_#{id}.jpg" : "logo_tall_#{family_name}.jpg"
        %img{src: CDO.code_org_url("/shared/images/courses/fill-150x110/#{image}")}
      .courseblock-span4.heading
        %h3= data_t_suffix('script.name', id, 'title')
        %h4= data_t_suffix('script.name', id, 'description_audience')
        .smalltext= data_t_suffix('script.name', id, 'description_short')

- elsif [Unit::COURSE1_NAME, Unit::COURSE2_NAME, Unit::COURSE3_NAME, Unit::COURSE4_NAME, Unit::ALGEBRA_NAME].include? id
  .courseblock-span6.courseblock-wide-large
    =link_to script_url(id) do
      .courseblock-span2.imgspan
        = image_tag(CDO.shared_image_url("courses/fit-150x100/logo_#{id}.jpg"))
      .courseblock-span4.heading
        %h3
          = data_t_suffix('script.name', id, 'title')
        %h4= data_t_suffix('script.name', id, 'description_audience')
        .smalltext= data_t_suffix('script.name', id, 'description')

- else
  .courseblock-span6.courseblock-wide-small
    = link_to script_url(id)  do
      .courseblock-span2.imgspan
        - image = (family_name.nil?) ? "logo_tall_#{id}.jpg" : "logo_tall_#{family_name}.jpg"
        %img{src: CDO.code_org_url("/shared/images/courses/fill-150x110/#{image}")}
      .courseblock-span4.heading
        %h3= data_t_suffix('script.name', id, 'title')
        .smalltext= data_t_suffix('script.name', id, 'description_short')

dashboard/app/views/shared/_emulate_print_media.html.haml
-if request.params.has_key? "emulate_print_media"
  = javascript_include_tag 'emulate-print-media.js'

dashboard/app/views/shared/_extra_links.html.haml
.extra-links
  %h4
    Extra Links:
    %a{id: 'levelbuilder-menu-toggle', href: '#', onclick: 'return extraLinksClick()'} [hide/show]
  .content
    = yield

:javascript

  var extraLinksBox;

  $().ready(function() {
    extraLinksBox = $(".extra-links .content");
    if (document.cookie.indexOf('hide-extra-links-menu') >= 0) {
      extraLinksBox.hide();
    }
  });

  // Dismiss this whole box.
  function extraLinksDismissClick() {
    $('.extra-links').remove();
  }

  // Toggles the visibility of the links, setting a cookie to preserve the
  // preference.
  function extraLinksClick() {
    extraLinksBox.toggle();
    if (extraLinksBox.is(":visible")) {
      // Clear the cookie using a blank value and a date in the past.
      document.cookie = "hide-extra-links-menu=; expires=Thu, 01 Jan 1970 00:00:00 UTC;";
    } else {
      // Set the cookie and make it expire far into the future.
      document.cookie="hide-extra-links-menu=true; expires=Fri, 31 Dec 9999 23:59:59 GMT;";
    }
    return false;
  }

dashboard/app/views/shared/_maybe_set_hoc_secret.html.haml
- if current_user && current_user.permission?(UserPermission::LEVELBUILDER)
  -# For levelbuilders, set a client-side secret that allows them to access restricted HOC levels.
  :javascript
    //<![CDATA[
    try {
      localStorage.setItem('hoc_secret', '#{DCDO.get("hoc_secret", nil)}');
    } catch(e) {}
    //]]>
- elsif params[:hoc_secret]
  -# Allow non-admins to specify the secret via a query string parameter.
  :javascript
    //<![CDATA[
    try {
      localStorage.setItem('hoc_secret', '#{escape_javascript(params[:hoc_secret])}')
    } catch(e) {}
    //]]>

dashboard/app/views/shared/_school_info.html.haml
- require 'country_codes'
- require 'state_abbr'
- require 'geocoder'

- location = Geocoder.search(request.ip).try(:first)
-# geocoder sometimes shows localhost's country as RD/Reserved
- us_ip = location.nil? || ['US', 'RD'].include?(location.country_code.to_s.upcase)
- existing_school_info ||= {}
- existing_school_info[:country] ||= 'US' if us_ip

- content_for(:head) do
  %script{src: webpack_asset_path('js/shared/_school_info.js')}

#pl-application-form
  #pl-application-facets.form-section
    .form-group#school-country-group
      .question School Country
      %select#school-country.form-control{name: "#{form_name}[country]", type: "select", required: false}
        %option{value: "", selected: true, disabled: true}
        - COUNTRY_CODE_TO_COUNTRY_NAME.each_key do |code|
          %option{value: code}= country_name_from_code(code)

    .form-group
      .question Select school type
      %select#school-type.form-control{name: "#{form_name}[school_type]", type: "select", required: false}
        %option{value: "", selected: true, disabled: true}
        %option{value: SchoolInfo::SCHOOL_TYPE_CHARTER} Charter
        %option{value: SchoolInfo::SCHOOL_TYPE_PRIVATE} Private
        %option{value: SchoolInfo::SCHOOL_TYPE_PUBLIC} Public
        %option{value: SchoolInfo::SCHOOL_TYPE_OTHER} Other

    .form-group{style: "display: none;"}
      .question State
      %select#school-state.form-control{name: "#{form_name}[school_state]", type: "select", required: false}
        %option{value: "", selected: true, disabled: true}
        - get_all_states_with_dc.each do |state_abbr, state_name|
          %option{value: state_abbr}= state_name

    .form-group{style: "display: none;"}
      .question District
      #school-district

        -# We'll apply the Selectize UI control to this input.
        %input#school-district-id.form-control{name: "#{form_name}[school_district_id]", type: "text", required: false}

        %label
          %input#school-district-other{name: "#{form_name}[school_district_other]", type: "checkbox", value: "true", style: "margin-top: 0px"}
          %span{style: "font-size: 12px"}
            Other district not listed above

        .form-group{style: "display: none;"}
          .question District Name
          %div.controls
            %input#school-district-name.form-control{name: "school_info[school_district_name]", type: "text", required: false, style: "width: calc(100% - 15px);"}

    .form-group{style: "display: none;"}
      .question School
      #school

        -# We'll apply the Selectize UI control to this input.
        %input#school-id.form-control{name: "#{form_name}[school_id]", type: "text", required: false}

        %label
          %input#school-other{name: "#{form_name}[school_other]", type: "checkbox", value: "true", style: "margin-top: 0px"}
          %span{style: "font-size: 12px"}
            Other school not listed above

    #no-schools-warning{style: "display: none; margin-bottom: 5px;"}
      .question No schools of that type were found in this district.

    -# '#school-name' is outside of '#school' so that we can still show it when the school dropdown is hidden.
    .form-group{style: "display: none;"}
      .question
        School Name
      %div.controls
        %input#school-name.form-control{name: "school_info[school_name]", type: "text", required: false, style: "width: calc(100% - 15px);"}

    .form-group{style: "display: none;"}
      .question School’s ZIP code
      %input#school-zipcode.form-control{name: "#{form_name}[school_zip]", type: "text", required: false}

    .form-group{style: "display: none;"}
      .question
        School Address
      %div.controls
        %textarea#school-address.form-control{name: "school_info[full_address]", required: false, rows: 4, maxlength: 255, style: "width: calc(100% - 15px);"}

:javascript

  $(document).ready(function() {
    var options = #{existing_school_info.to_json};
    var suppressScrolling = #{!!(local_assigns[:suppress_scrolling])};
    options['suppressScrolling'] = suppressScrolling;
    options['assumeUsa'] = #{!!(local_assigns[:assume_usa])};

    // Send through some values that the JavaScript will need.
    window.schoolInfoManager = new SchoolInfoManager(options);
  });

dashboard/app/views/shared/_sharing_meta_tags.html.haml
-# only works for pages that have a @level
- if @level && @level.game.supports_sharing?
  - content_for :og do
    = tag 'meta', name: 'viewport', content: 'initial-scale=1'

    -# facebook boilerplate
    = tag 'meta', property: 'fb:app_id', content: '500177453358606'
    = tag 'meta', property: 'og:site_name', content: 'Code.org'
    = tag 'meta', property: 'og:type', content: 'article'
    = tag 'meta', property: 'article:publisher', content: 'https://www.facebook.com/Code.org'

    -# twitter boilerplate
    = tag 'meta', name: 'twitter:site', content: '@codeorg'

    - if @level.game.app == Game::DANCE || @level.game.app == Game::ARTIST
      = tag 'meta', name: 'twitter:card', content: 'summary'
    - else
      = tag 'meta', name: 'twitter:card', content: 'photo'

    - meta_image_width = 400
    - meta_image_height = 400

    -# several meta tags are the same for facebook/og and twitter
    - {og: 'property', twitter: 'name'}.each do |namespace, attr|
      = tag 'meta', attr => "#{namespace}:title", content: t('share_code.check_out_what_i_made')
      = tag 'meta', attr => "#{namespace}:description", content: t('share_code.og_description')
      = tag 'meta', attr => "#{namespace}:url", content: request.original_url

      - if @project_image
        = tag 'meta', attr => "#{namespace}:image", content: @project_image
        = tag 'meta', attr => "#{namespace}:image:secure_url", content: @project_image
      - else
        = tag 'meta', attr => "#{namespace}:image", content: meta_image_url(level_source: @level_source, level: @level)
        = tag 'meta', attr => "#{namespace}:image:secure_url", content: meta_image_url(level_source: @level_source, level: @level)
      = tag 'meta', attr => "#{namespace}:image:width", content: meta_image_width
      = tag 'meta', attr => "#{namespace}:image:height", content: meta_image_height

    = tag :meta, name: 'mobile-web-app-capable', content: 'yes'
    = tag :meta, name: 'apple-mobile-web-app-capable', content: 'yes'
    = tag :meta, name: 'apple-mobile-web-app-status-bar-style', content: 'black-translucent'
    - if @level_source.try(:level_source_image).try(:image)
      = tag :link, rel: 'apple-touch-icon', href: meta_image_url(level_source: @level_source, level: @level)
    - elsif @level.game.flappy?
      = tag :link, rel: 'apple-touch-icon', href: asset_url('flappy_icon.png')
    - else
      = tag :link, rel: 'apple-touch-icon', href: asset_url('logo_noalpha.png')