dashboard/config/routes.rb
# For documentation see, e.g., http://guides.rubyonrails.org/routing.html.

Dashboard::Application.routes.draw do
  # Override Error Codes
  get "404", to: "application#render_404", via: :all

  # Redirect studio.code.org/courses to code.org/students
  get "/courses", to: redirect(CDO.code_org_url("/students"))

  constraints host: CDO.codeprojects_hostname do
    # Routes needed for the footer on weblab share links on codeprojects
    get '/weblab/footer', to: 'projects#weblab_footer'
  end

  # This matches any host that is not the codeprojects hostname
  constraints host: /^(?!#{CDO.codeprojects_hostname})/ do
    # React-router will handle sub-routes on the client.
    get 'teacher_dashboard/sections/:section_id/parent_letter', to: 'teacher_dashboard#parent_letter'
    get 'teacher_dashboard/sections/:section_id/*path', to: 'teacher_dashboard#show', via: :all
    get 'teacher_dashboard/sections/:section_id', to: 'teacher_dashboard#show'

    resources :survey_results, only: [:create], defaults: {format: 'json'}

    resource :pairing, only: [:show, :update]

    resources :user_levels, only: [:update, :destroy]
    post '/delete_predict_level_progress', to: 'user_levels#delete_predict_level_progress'
    get '/user_levels/get_token', to: 'user_levels#get_token'
    get '/user_levels/level_source/:script_id/:level_id', to: 'user_levels#get_level_source'

    patch '/api/v1/user_scripts/:script_id', to: 'api/v1/user_scripts#update'

    get '/download/:product', to: 'hoc_download#index'

    get '/terms-and-privacy', to: 'home#terms_and_privacy'
    get '/dashboardapi/terms-and-privacy', to: "home#terms_and_privacy"
    get '/dashboardapi/hoc-courses-teacher-guides', to: "home#hoc_courses_teacher_guides"
    get '/dashboardapi/hoc-courses-challenge', to: "home#hoc_courses_challenge"

    get "/home", to: "home#home"

    get "/congrats", to: "congrats#index"

    get "/incubator", to: "incubator#index"
    get "/musiclab", to: redirect(CDO.code_org_url("/music"))
    get "/projectbeats", to: redirect(CDO.code_org_url("/music"))
    get "/musiclab/menu", to: "musiclab#menu"
    get "/musiclab/gallery", to: "musiclab#gallery"
    get "/musiclab/embed", to: "musiclab#embed"
    get "/musiclab/analytics_key", to: "musiclab#get_analytics_key"

    resources :activity_hints, only: [:update]

    resources :hint_view_requests, only: [:create]
    resources :authored_hint_view_requests, only: [:create]

    resources :puzzle_ratings, only: [:create]
    resources :callouts
    resources :videos do
      collection do
        get 'test'
      end
    end

    resources :images, only: [:new]

    get 'maker/home', to: 'maker#home'
    get 'maker/setup', to: 'maker#setup'

    # Media proxying
    get 'media', to: 'media_proxy#get', format: false

    # XHR proxying
    get 'xhr', to: 'xhr_proxy#get', format: false

    get 'redirected_url', to: 'redirect_proxy#get', format: false

    # Code docs are off of curriculum builder as of spring 2022.
    get 'docs/', to: 'programming_environments#docs_index'
    get 'docs/:programming_environment_name', to: 'programming_environments#docs_show', constraints: {programming_environment_name: /(applab|gamelab|spritelab|weblab)/}
    get 'docs/:programming_environment_name/:programming_expression_key', constraints: {programming_environment_name: /(applab|gamelab|spritelab|weblab)/, programming_expression_key: /#{CurriculumHelper::KEY_CHAR_RE}+/o}, to: 'programming_expressions#docs_show'
    get 'docs/:programming_environment_name/:programming_expression_key/index.html', constraints: {programming_environment_name: /(applab|gamelab|spritelab|weblab)/, programming_expression_key: /#{CurriculumHelper::KEY_CHAR_RE}+/o}, to: 'programming_expressions#docs_show'

    resources :programming_environments, only: [:index, :show], param: 'name', path: '/docs/ide/' do
      resources :programming_expressions, param: 'programming_expression_key', constraints: {programming_expression_key: /#{CurriculumHelper::KEY_CHAR_RE}+/o}, path: '/expressions' do
        member do
          get :show, to: 'programming_expressions#show_by_keys'
        end
      end
      resources :programming_classes, param: 'programming_class_key', constraints: {programming_class_key: /#{CurriculumHelper::KEY_CHAR_RE}+/o}, path: '/classes' do
        member do
          get :show, to: 'programming_classes#show_by_keys'
        end
      end
    end

    # Data docs are off of curriculum builder as of fall 2022.
    get 'docs/concepts/data-library', to: 'data_docs#index'
    get 'docs/concepts/data-library/:key', param: :key, constraints: {data_doc_key: /#{CurriculumHelper::KEY_CHAR_RE}+/o}, to: 'data_docs#show'

    # There are still old curricula that live on curriculum.code.org.
    # There are also old levels that point to docs on curriculum.code.org.
    # For both, fall back to old proxying logic.
    get 'docs/*path', to: 'curriculum_proxy#get_doc'
    get 'curriculum/*path', to: 'curriculum_proxy#get_curriculum'

    get '/catalog', to: 'curriculum_catalog#index'

    # User-facing section routes
    resources :sections, only: [:show, :new, :edit] do
      member do
        post 'log_in'
      end
    end
    # Section API routes (JSON only)
    concern :section_api_routes do
      resources :sections, only: [:index, :show, :create, :update, :destroy] do
        resources :students, only: [:index, :update], controller: 'sections_students' do
          collection do
            post 'bulk_add'
            get 'completed_levels_count'
          end
          member do
            post 'remove'
          end
        end
        member do
          post 'join'
          post 'leave'
          post 'update_sharing_disabled'
          get 'code_review_groups'
          post 'code_review_groups', to: 'sections#set_code_review_groups'
          post 'code_review_enabled', to: 'sections#set_code_review_enabled'
          post 'ai_tutor_enabled', to: 'sections#set_ai_tutor_enabled'
        end
        collection do
          get 'membership'
          get 'valid_course_offerings'
          get 'available_participant_types'
          get 'require_captcha'
        end
      end
    end

    # Used in react assessments tab
    concern :assessments_routes do
      resources :assessments, only: [:index] do
        collection do
          get 'section_responses'
          get 'section_surveys'
          get 'section_feedback'
        end
      end
    end

    post '/dashboardapi/sections/transfers', to: 'transfers#create'
    post '/api/sections/transfers', to: 'transfers#create'

    get '/sh/:id', to: redirect('/c/%{id}')
    get '/sh/:id/:action_id', to: redirect('/c/%{id}/%{action_id}')

    get '/u/:id', to: redirect('/c/%{id}')
    get '/u/:id/:action_id', to: redirect('/c/%{id}/%{action_id}')

    # These links should no longer be created (August 2017), though we will continue to support
    # existing links. Instead, create /r/ links.
    resources :level_sources, path: '/c/', only: [:show, :edit, :update] do
      member do
        get 'generate_image'
        get 'original_image'
      end
    end
    # These routes are being created to replace the /c/ routes (August 2017) so as to include the ID
    # of the sharing user in the URL. Doing so allows us to block showing the level source if the user
    # deletes themself.
    resources :obfuscated_level_sources, path: '/r/', controller: :level_sources, param: :level_source_id_and_user_id, only: [:show, :edit, :update] do
      member do
        get 'generate_image'
        get 'original_image'
      end
    end

    get '/share/:id', to: redirect('/c/%{id}')

    devise_scope :user do
      get '/oauth_sign_out/:provider', to: 'sessions#oauth_sign_out', as: :oauth_sign_out
      post '/users/begin_sign_up', to: 'registrations#begin_sign_up'
      post '/users/finish_sign_up', to: 'registrations#new'
      patch '/dashboardapi/users', to: 'registrations#update'
      patch '/users/upgrade', to: 'registrations#upgrade'
      patch '/users/set_student_information', to: 'registrations#set_student_information'
      patch '/users/email', to: 'registrations#set_email'
      patch '/users/parent_email', to: 'registrations#set_parent_email'
      patch '/users/user_type', to: 'registrations#set_user_type'
      get '/users/cancel', to: 'registrations#cancel'
      post '/users/auth/:id/disconnect', to: 'authentication_options#disconnect'
      get '/users/migrate_to_multi_auth', to: 'registrations#migrate_to_multi_auth'
      get '/users/demigrate_from_multi_auth', to: 'registrations#demigrate_from_multi_auth'
      get '/users/to_destroy', to: 'registrations#users_to_destroy'
      get '/reset_session', to: 'sessions#reset'
      get '/lockout', to: 'sessions#lockout'
      get '/users/existing_account', to: 'registrations#existing_account'
      get '/users/edit', to: 'registrations#edit'
    end
    devise_for :users, controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      confirmations: 'confirmations',
      sessions: 'sessions',
      passwords: 'passwords'
    }
    get 'discourse/sso' => 'discourse_sso#sso'

    root to: "home#index"
    get '/home_insert', to: 'home#home_insert'
    get '/health_check', to: 'home#health_check'
    namespace :home do
      HomeController.instance_methods(false).each do |action|
        get action, action: action
      end
    end

    resources :p, path: '/p/', only: [:index] do
      collection do
        ProjectsController::STANDALONE_PROJECTS.each do |key, value|
          get '/' + key.to_s, to: 'projects#redirect_legacy', key: value[:name], as: key.to_s
        end
        get '/', to: redirect('/projects')
      end
    end

    get "/gallery", to: redirect("/projects/public")

    get 'projects/featured', to: 'projects#featured'
    delete '/featured_projects/:channel_id', to: 'featured_projects#destroy'

dashboard/app/views/home/_admin.html.haml
- if current_user && current_user.admin?
  = render layout: 'shared/extra_links' do
    %div
      = link_to 'Admin Page Directory', admin_directory_path
    %div{style: "margin-top: 10px;"} Support tools
    %ul
      %li= link_to 'Assume Identity', assume_identity_form_path
      %li= link_to 'Reset Password', new_user_password_path
      %li= link_to 'Account Repair', account_repair_form_path
      %li= link_to 'Look up section', lookup_section_path
      %li= link_to 'Find Users', find_students_path
      %li= link_to 'User progress', user_progress_form_path
      %li= link_to 'User projects', user_projects_form_path
      %li= link_to 'Gatekeeper', gatekeeper_show_path
      %li= link_to 'DCDO', dcdo_show_path
      %li= link_to 'Grant Permissions/Privileges', permissions_form_path
      %li= link_to 'Videos', videos_path

dashboard/app/views/home/_all_courses.html.haml
:ruby
  # The locale the user has set in the browser e.g. en-US.
  locale ||= nil
  show_state = Gatekeeper.allows('logged_in_studio_homepage', default: true)

  tall_blocks = [
    Unit::COURSE1_NAME,
    Unit::COURSE2_NAME,
    Unit::COURSE3_NAME,
    Unit::COURSE4_NAME,
    Unit::MINECRAFT_AQUATIC_NAME,
    Unit::MINECRAFT_HERO_NAME,
    Unit::STARWARS_NAME,
    Unit::FROZEN_NAME,
    Unit::HOC_NAME,
    Unit::FLAPPY_NAME,
    Unit::INFINITY_NAME,
    Unit::PLAYLAB_NAME,
    Unit::ARTIST_NAME,
    Unit::APPLAB_INTRO,
    Unit::DANCE_PARTY_NAME,
    Unit::DANCE_PARTY_2019_NAME,
    Unit::OCEANS_NAME
  ]

  wide_blocks = [
    Unit::TWENTY_HOUR_NAME,
    "unplugged",
  ]

  # Family name for a set of courses. A block will be generated for the recommended one.
  family_wide_blocks = [
    Unit::EXPRESS,
    Unit::PREEXPRESS,
  ]

  # Family name for a set of courses. A block will be generated for the recommended one.
  family_tall_blocks = [
    Unit::COURSEA,
    Unit::COURSEB,
    Unit::COURSEC,
    Unit::COURSED,
    Unit::COURSEE,
    Unit::COURSEF,
  ]

.all-course-blocks
  - tall_blocks.each do |script_name|
    %div{id: script_name}
      = render partial: 'shared/course_tall_block', locals: { id: script_name, family_name: nil}

  - wide_blocks.each do |script_name|
    %div{id: script_name}
      = render partial: 'shared/course_wide_block', locals: { id: script_name, view: "small" }

  -# Creates a block for the recommended course version in the given course family.
  - family_tall_blocks.each do |family_name|
    - script = Unit.latest_stable_version(family_name, locale: locale)
    - next unless script
    %div{id: family_name}
      = render partial: 'shared/course_tall_block', locals: { id: script.name, family_name: family_name}

  -# Creates a block for the recommended course version in the given course family.
  - family_wide_blocks.each do |family_name|
    - script = Unit.latest_stable_version(family_name, locale: locale)
    - next unless script
    %div{id: family_name}
      = render partial: 'shared/course_wide_block', locals: { id: script.name, view: "small", family_name: family_name }

.csf-courses-header
  .row
    .span12.twolineheader!= t('home.heading_elementary_markdown', markdown: true)

dashboard/app/views/home/_donor_footer.html.haml
#donor-footer{ style: "background: url(#{asset_path('donor-footer-background.png')}); background-size: cover" }
  %h1
    Code.org thanks our donors
  %p
    Our vision is that every student in every school should have the opportunity to learn computer science. The impact of our work is amplified and made possible with help from our amazing partners.
  %h3
    - if current_user.teacher?
      Your classroom's free use of Code.org is made possible by:
    - else
      Your free education on Code.org is made possible by:
  - @homepage_data[:donorFooterOptions][:logos].each do |logo|
    = image_tag asset_path("donor_logos/#{current_user.school_donor_name}/#{logo.split('/').last}"), class: 'logo'
  - if current_user.teacher? && @homepage_data[:donorFooterOptions][:donorName] == "Amazon"
    %div
      %p.resources
        Amazon is offering free resources for Code.org classrooms.
        %a.learn-more{ href: CDO.code_org_url('amazon-future-engineer') }
          %strong
            Learn more

dashboard/app/views/home/_homepage.html.haml
- content_for(:head) do
  %script{src: webpack_asset_path('js/home/_homepage.js'), data: {homepage: @homepage_data.to_json}}
  - if @homepage_data[:showCensusBanner]
    %script{type: "text/javascript", src: "https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.5.1/mapbox-gl-geocoder.min.js"}
    %link{rel: "stylesheet", type: "text/css", href: "https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.5.1/mapbox-gl-geocoder.css"}
%link{href: "/shared/css/phase1-design-system.css", rel: "stylesheet"}
-# Components generated by HAML which might be pulled in and displayed by the React model.
.hiddenComponents{style: "display: none"}
  #flashes
    = show_flashes.html_safe

.clear{style: "clear: both"}

-# In-page reminders and surveys
- if current_user
  - if current_user.teacher?
    #teacher_reminders
      - unless current_user.accepted_latest_terms?
        = render partial: 'layouts/implicit_new_user_terms_interstitial'
      - if show_diversity_survey? SurveyResult::DIVERSITY_2024
        = render partial: 'home/survey_diversity'

#homepage-container

dashboard/app/views/home/_levelbuilder.html.haml
- if current_user && current_user.permission?(UserPermission::LEVELBUILDER)
  = render layout: 'shared/extra_links' do
    %li= link_to 'Videos', videos_path
    %li= link_to 'Images', '/images/new'
    %li
      = link_to 'Scripts', scripts_path
      = link_to '(Update all)', scripts_path(rake: '1'), data: { confirm: 'Are you sure want to re-seed script data?'}
    %li= link_to t('builder.manage'), levels_path
    %li= link_to 'Block Pools', pools_path
    %li= link_to 'Shared Functions', shared_blockly_functions_path
    %li= link_to 'Helper Libraries', libraries_path
    %li= link_to 'Gallery', 'projects/public'
    %li= link_to 'Foorm Surveys (preview)', 'foorm/forms/editor'
    %li= link_to '(BETA) Sprite Lab Sprite Management', 'sprites'
    %li= link_to 'Helpful Links', helpful_links_path

dashboard/app/views/home/_nav.html.haml
- return unless current_user

- active ||= nil
%a{name: active}
.row.navcontainer
  .span12{style: 'margin-left: 0'}
    %ul.nav.nav-pills{style: 'margin: 0'}
      - if current_user && Queries::ScriptActivity.working_on_user_scripts(current_user).any?
        %li{class: active == :working ? 'active' : ''}
          %a{href: '#working'}= I18n.t('studio.courses_working_on')
      - if current_user && Queries::ScriptActivity.completed_user_scripts(current_user).any?
        %li{class: active == :completed ? 'active' : ''}
          %a{href: '#completed'}= I18n.t('studio.completed_courses')
      %li{class: active == :all ? 'active' : ''}
        %a{href: '#all'}= I18n.t('studio.all_courses')

dashboard/app/views/home/_projects.html.haml
.course_progress
  %h3.whitetext{style: 'margin: 0'}
    = t("project.projects")
  = link_to projects_path do
    %button.btn.btn-primary.button-continue#continue_button{style: 'margin: 0'}= t('project.view_all')

dashboard/app/views/home/_survey_diversity.haml
#diversity_survey
  #surveythanks{style: "display: none; "}
    Thank you for telling us about your students!

  #surveybody
    #headingarea
      %h2 Optional: Help us track our progress toward improving diversity in computer science
      .subtext
        To protect your students’ privacy, we will not ask students younger than 13 for this information. Therefore, this information will not be linked to their specific accounts.
        (See our
        = succeed '.)' do
          %a#privacylink{href: CDO.code_org_url('/privacy'), target: "_blank"} privacy policy

    = form_for(SurveyResult.new, html: {id: 'survey', onsubmit: "return window.submitSurvey(true)"}) do |f|
      .survey_questions
        %ol
          %li
            Of your students using Code.org's courses, how many identify as:
        .dots
          - SurveyResult::ETHNICITIES.each do |key, value|
            %input#ethnicity_input{maxlength: "3", name: "survey[diversity_#{key}]", placeholder: "0"}
            = value
            %br/

      %input{type: "hidden", name: "survey[kind]", value: SurveyResult::DIVERSITY_2024}

      #submit
        %button.btn-primary#submitSurvey{type: "submit"} Submit
        %button#noanswer{onclick: "return submitSurvey(false)"} Prefer not to answer
%br/

:javascript

  function submitSurvey(submittedValue)
  {
    // make sure each ethnicity is a positive integer
    $("#ethnicity_input").each(function(index) {
      $(this).val($(this).val().replace(/[^0-9]/g, ''));
    });

    if (submittedValue)
    {
      $("#surveybody").hide();
      $("#surveythanks").fadeIn();
    }
    else
    {
      $("#survey")[0].reset();
      $("#diversity_survey").hide();
    }

    $.ajax({
      type: 'POST',
      url: $("#survey").attr('action'),
      data: $("#survey").serialize(),
      dataType: 'json'
    });

    // scroll to top of page so that user sees "thank you" even if they had scrolled down
    // to fill out survey.

    $('html,body').animate({scrollTop:0}, 100);

    return false;
  }

dashboard/app/views/home/_tos_and_privacy.html.haml
- @page_title = 'Terms of Service, Privacy Policy, and Privacy Notice'

%h1 Terms of Service
= render partial: 'home/tos'

%hr

%h1 Privacy Policy
= render partial: 'home/privacy'

dashboard/app/views/home/index.html.haml
- content_for :og do
  = tag 'meta', property: 'og:title', content: t('share.title')
  = tag 'meta', property: 'og:image', content: CDO.studio_url(CDO.shared_image_url('share/girl_cropped.jpg'), 'https:')
  = tag 'meta', property: 'og:description', content: t('share.description')

-if current_user&.school_donor_name
  - content_for :above_footer_content do
    = render partial: 'home/donor_footer'

-# Student modal
- if RaceInterstitialHelper.show?(current_user) || @force_race_interstitial
  = render partial: 'layouts/race_interstitial'

-# Teacher modals
- if current_user && current_user.teacher? && !current_user.accepted_latest_terms?
  - current_user.update_user_tos_version_accept()
  = render partial: 'layouts/implicit_new_user_terms_interstitial'
- elsif InitialSectionCreationInterstitialHelper.show?(current_user)
  = render partial: 'layouts/initial_section_creation_interstitial'
- elsif @show_section_creation_celebration_dialog
  = render partial: 'layouts/section_creation_celebration_dialog'
- elsif (SchoolInfoInterstitialHelper.show_confirmation_dialog?(current_user) || @force_school_info_confirmation_dialog) && !params[:courseVersionId]
  - SchoolInfoInterstitialHelper.update_last_seen_timestamp(current_user)
  = render partial: 'layouts/school_info_confirmation_dialog'
- elsif SchoolInfoInterstitialHelper.show?(current_user) || @force_school_info_interstitial
  - SchoolInfoInterstitialHelper.update_last_seen_timestamp(current_user)
  = render partial: 'layouts/school_info_interstitial', locals: {show_header: false, user: current_user, form_name: "user[school_info_attributes]"}

- if current_user
  = render partial: 'home/homepage'

%br/
%br/
%br/

= render partial: 'home/admin'
= render partial: 'home/levelbuilder'

:javascript
  $("#section_code").placeholder();